"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

DEBUG=True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}

# If you need CORS for frontend access
AWS_S3_CORS = [
    {
        'AllowedOrigins': ['*'],
        'AllowedMethods': ['GET', 'POST', 'PUT'],
        'AllowedHeaders': ['*'],
    }
]

# AWS S3 Configuration - Force global endpoint
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = 'us-east-1'  # Force us-east-1 for global endpoint

# Force specific S3 settings for problematic buckets
AWS_S3_ADDRESSING_STYLE = 'path'
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_CUSTOM_DOMAIN = None
AWS_DEFAULT_ACL = None
AWS_S3_FILE_OVERWRITE = False
AWS_S3_URL_PROTOCOL = 'https:'

# Explicit endpoint configuration
AWS_S3_ENDPOINT_URL = 'https://s3.amazonaws.com'

# Storage backends
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATICFILES_STORAGE = 'storages.backends.s3boto3.StaticS3Boto3Storage'

AWS_LOCATION = 'uploads'
# CKEditor uploads inside "uploads/content/ckeditor/"
CKEDITOR_UPLOAD_PATH = "uploads/content/ckeditor/"


# URL configuration
MEDIA_URL = f"https://s3.amazonaws.com/{os.getenv('AWS_STORAGE_BUCKET_NAME')}/"

# settings.py - Add detailed logging for admin
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.contrib.admin': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
        'storages': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}

# Also add this for more verbose S3 operations
AWS_S3_FILE_OVERWRITE = True  # Temporarily for testing

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-muc7ruzx=f)x!-b#y(*33naudgpva)#uv-%$p$%hb*oi0qdbgy'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True

ALLOWED_HOSTS = [
    "offplan-backend.onrender.com",  # ✅ Your Render service URL
    "localhost",                     # optional for local dev
    "127.0.0.1",
    "192.168.1.50",
    "offplan.market",
    "www.offplan.market",
]

CSRF_TRUSTED_ORIGINS = [
    "https://offplanmarket.vercel.app",
    "https://offplan-backend.onrender.com",
    "https://offplan.market",
]

CORS_ALLOWED_ORIGINS = [
    "https://offplanmarket.vercel.app",
    "http://localhost:3000",  # for development
    "https://offplan-backend.onrender.com",
    "https://offplan.market",
]

CKEDITOR_CONFIGS = {
    'default': {
        'htmlEncodeOutput': False,  # This prevents double encoding
        'entities': False,
        'basicEntities': False,
    }
}



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    'api',  # Your app for agent management
    'api.blog',
    'drf_yasg',
    'corsheaders',
    'storages',
    'ckeditor',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
}

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'offplan_backend_agent', 'api', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
        'OPTIONS': {
            'options': '-c search_path=public',
#            'sslmode': 'require'
        }
    }
}



SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,  # 👈 Prevents Django login for Swagger
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
